### DISCUSSION TITLE
More than one PDU session

### DISCUSSION THREAD

**Discussion by kedargaonkar** [aligungr/UERANSIM#286] [Ideas]
Hello,

Is it possible to create more than one PDU sessions for the simulated UEs?

- Kedar

**Comment by aligungr** [comment]
Hello Kedar,

Yes you can use multiple PDU sessions. Indeed `sessions` fields is a list of PDU sessions, so you can add another PDU session to the UE config yaml.

Example:

```
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1
      sd: 1
    emergency: false
  - type: 'ims'
    apn: 'internet'
    slice:
      sst: 1
      sd: 1
    emergency: false
```

Or, you can always use `nr-cli` to establish or release a PDU session at runtime.
