### DISCUSSION TITLE
Why UE cannot receive ICMP response from gNB (UERANSIM + Free5GC)

### DISCUSSION THREAD

**Discussion by Shanola** [aligungr/UERANSIM#467] [Q&A]
Hello @aligungr and community,

I'm using UERANSIM v3.2.3 and Free5GC v3.0.6.

Currently I'm building an environment based on [Environment setup of multiple SMF, DNN, and UPF (including ULCL)](https://www.youtube.com/watch?v=AEMrjKRWarw&ab_channel=free5GC) of Free5GC, but to divided one UERANSIM VM into 2 VMs (one is UE and the other one is gNB)

- Original topology (screeshot from Free5GC's video):
   ![image](https://user-images.githubusercontent.com/80759330/147878541-fbfc30c2-6d45-433f-96fa-27e0ef715533.png)

- New topology (divide UERANSIM VM into 2 VMs):
   ![image](https://user-images.githubusercontent.com/80759330/147878387-4a779c83-bcc5-4f53-a4af-b5b11c0b7b2a.png)

I've successfully test original topology with **Ping** command, but when I divided UERANSIM VM into 2 VMs, there're two results:

1. UE1 ping to 8.8.8.8 (DNN: Internet): **Failed**
2. UE2 ping to 8.8.8.8 (DNN: IMS): **Success**

**I found that the ICMP request can go to the internet, but **the ICMP reply stops at gNB**, which means gNB receives ICMP reply from I-UPF, but it doesn't forward the packet anymore!**

So I wonder if I miss some configuration or misuse the UERANSIM software?

Here are my YAML files:
- free5gc-ue1.yaml
  ```
  # IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
  supi: 'imsi-208930000000003'
  # Mobile Country Code value of HPLMN
  mcc: '208'
  # Mobile Network Code value of HPLMN (2 or 3 digits)
  mnc: '93'
  
  # Permanent subscription key
  key: '8baf473f2f8fd09487cccbd7097c6862'
  # Operator code (OP or OPC) of the UE
  op: '8e27b6af0e692e750f32667a3b14605d'
  # This value specifies the OP type and it can be either 'OP' or 'OPC'
  opType: 'OPC'
  # Authentication Management Field (AMF) value
  amf: '8000'
  # IMEI number of the device. It is used if no SUPI is provided
  imei: '356938035643803'
  # IMEISV number of the device. It is used if no SUPI and IMEI is provided
  imeiSv: '4370816125816151'
  
  # List of gNB IP addresses for Radio Link Simulation
  gnbSearchList:
    - 192.168.0.131
  
  # UAC Access Identities Configuration
  uacAic:
    mps: false
    mcs: false
  
  # UAC Access Control Class
  uacAcc:
    normalClass: 0
    class11: false
    class12: false
    class13: false
    class14: false
    class15: false
  
  # Initial PDU sessions to be established
  sessions:
    - type: 'IPv4'
      apn: 'internet'
      slice:
        sst: 0x01
        sd: 0x010203
  
  # Configured NSSAI for this UE by HPLMN
  configured-nssai:
    - sst: 0x01
      sd: 0x010203
  
  # Default Configured NSSAI for this UE
  default-nssai:
    - sst: 1
      sd: 1
  
  # Supported encryption algorithms by this UE
  integrity:
    IA1: true
    IA2: true
    IA3: true
  
  # Supported integrity algorithms by this UE
  ciphering:
    EA1: true
    EA2: true
    EA3: true
  
  # Integrity protection maximum data rate for user plane
  integrityMaxRate:
    uplink: 'full'
    downlink: 'full'
  ```
- free5gc-ue2.yaml
  ```
  # IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
  supi: 'imsi-208930000000004'
  # Mobile Country Code value of HPLMN
  mcc: '208'
  # Mobile Network Code value of HPLMN (2 or 3 digits)
  mnc: '93'
  
  # Permanent subscription key
  key: '8baf473f2f8fd09487cccbd7097c6862'
  # Operator code (OP or OPC) of the UE
  op: '8e27b6af0e692e750f32667a3b14605d'
  # This value specifies the OP type and it can be either 'OP' or 'OPC'
  opType: 'OPC'
  # Authentication Management Field (AMF) value
  amf: '8000'
  # IMEI number of the device. It is used if no SUPI is provided
  imei: '356938035643803'
  # IMEISV number of the device. It is used if no SUPI and IMEI is provided
  imeiSv: '4370816125816151'
  
  # List of gNB IP addresses for Radio Link Simulation
  gnbSearchList:
    - 192.168.0.131
  
  # UAC Access Identities Configuration
  uacAic:
    mps: false
    mcs: false
  
  # UAC Access Control Class
  uacAcc:
    normalClass: 0
    class11: false
    class12: false
    class13: false
    class14: false
    class15: false
  
  # Initial PDU sessions to be established
  sessions:
    - type: 'IPv4'
      apn: 'IMS'
      slice:
        sst: 0x01
        sd: 0x112233
  
  # Configured NSSAI for this UE by HPLMN
  configured-nssai:
    - sst: 0x01
      sd: 0x112233
  
  # Default Configured NSSAI for this UE
  default-nssai:
    - sst: 1
      sd: 1
  
  # Supported encryption algorithms by this UE
  integrity:
    IA1: true
    IA2: true
    IA3: true
  
  # Supported integrity algorithms by this UE
  ciphering:
    EA1: true
    EA2: true
    EA3: true
  
  # Integrity protection maximum data rate for user plane
  integrityMaxRate:
    uplink: 'full'
    downlink: 'full'
  ```
- free5gc-gnb.yaml
  ```
  mcc: '208'          # Mobile Country Code value
  mnc: '93'           # Mobile Network Code value (2 or 3 digits)
  
  nci: '0x000000010'  # NR Cell Identity (36-bit)
  idLength: 32        # NR gNB ID length in bits [22...32]
  tac: 1              # Tracking Area Code
  
  linkIp: 192.168.0.131   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
  ngapIp: 172.16.2.1   # gNB's local IP address for N2 Interface (Usually same with local IP)
  gtpIp: 172.16.3.1    # gNB's local IP address for N3 Interface (Usually same with local IP)
  
  # List of AMF address information
  amfConfigs:
    - address: 172.16.2.100
      port: 38412
  
  # List of supported S-NSSAIs by this gNB
  slices:
    - sst: 0x1
      sd: 0x010203
    - sst: 0x1
      sd: 0x112233
  
  # Indicates whether or not SCTP stream number errors should be ignored.
  ignoreStreamIds: true
  ```

There's my setting note which's more detail, thank you!
[multiple SMF, UPF with seperate UE and gNB](https://hackmd.io/@ptzling310/rymM1lzit)
