### ISSUE TITLE
Name resolution of gNB IP address

### ISSUE THREAD

**Issue by raoufkh** [aligungr/UERANSIM#245]
As mentionned in this [issue](https://github.com/aligungr/UERANSIM/issues/233), I'm trying to deploy the UERANSIM on top of Kubernetes.

Pods are the deployment unit in Kubernetes and I'm trying to deploy the gNB and the UE in 2 different Pods.

Since Pods' IP addresses are highly variable, it is recommended to use a Kubernetes [service](https://kubernetes.io/docs/concepts/services-networking/service/) to expose the Pods. Then, another applications can use the name of the service to access the Pod in the backend

In my case, I've created a service to expose the gNB Pod:
```
apiVersion: v1
kind: Service
metadata:
  name: gnb-service
  labels:
    app: ueransim
    component: gnb
spec:
  type: ClusterIP
  ports:
    - name: gnb-ue
      port: 4997
      protocol: UDP
  selector:
    app: ueransim
    component: gnb
```
And than I've passed its name to the UE:
```
    gnbSearchList:
      - {{ .Values.gnb.service.name }}
```  
Then, I realized that the UE expect only an IP address and not a name:
```
UERANSIM v3.0.1
[2021-01-30 05:31:55.116] [nas] [debug] NAS layer started
[2021-01-30 05:31:55.116] [rrc] [debug] RRC layer started
[2021-01-30 05:31:55.116] [nas] [info] UE switches to state: MM-DEREGISTERED/PLMN-SEARCH
terminate called after throwing an instance of 'LibError'
  what():  Bad Inet address: gnb-service No such file or directory
```
This can be solved by writing a script that replace the gNB service name by the corresponding IP address in the UE configuration, but I would like to want if you plan to add this functionality in the future releases  (name resolution) as it is very important in environments like Kubernetes.
