### ISSUE TITLE
UE fails Authentication Check

### ISSUE THREAD

**Issue by cglewis** [aligungr/UERANSIM#361]
```
gnb              | [2021-07-02 18:50:13.343] [rrc] [debug] UE[3] new signal detected
ue1              | [2021-07-02 18:50:13.344] [rrc] [debug] New signal detected for cell[1], total [1] cells in coverage
ue1              | [2021-07-02 18:50:13.344] [nas] [info] Selected plmn[001/01]
gnb              | [2021-07-02 18:50:13.344] [rrc] [info] RRC Setup for UE[3]
ue1              | [2021-07-02 18:50:13.344] [rrc] [info] Selected cell plmn[001/01] tac[1] category[SUITABLE]
ue1              | [2021-07-02 18:50:13.344] [nas] [info] UE switches to state [MM-DEREGISTERED/PS]
ue1              | [2021-07-02 18:50:13.344] [nas] [info] UE switches to state [MM-DEREGISTERED/NORMAL-SERVICE]
ue1              | [2021-07-02 18:50:13.344] [nas] [debug] Initial registration required due to [MM-DEREG-NORMAL-SERVICE]
gnb              | [2021-07-02 18:50:13.345] [ngap] [debug] Initial NAS message received from UE[3]
amf              | 07/02 18:50:13.345: [amf] INFO: InitialUEMessage (../src/amf/ngap-handler.c:361)
amf              | 07/02 18:50:13.345: [amf] INFO: [Added] Number of gNB-UEs is now 1 (../src/amf/context.c:1961)
amf              | 07/02 18:50:13.345: [amf] INFO:     RAN_UE_NGAP_ID[3] AMF_UE_NGAP_ID[3] TAC[1] CellID[0x10] (../src/amf/ngap-handler.c:497)
ue1              | [2021-07-02 18:50:13.344] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
ue1              | [2021-07-02 18:50:13.344] [nas] [debug] Sending Initial Registration
amf              | 07/02 18:50:13.345: [amf] INFO: [suci-0-001-01-0000-0-0-0000000001] Unknown UE by SUCI (../src/amf/context.c:1341)
amf              | 07/02 18:50:13.345: [amf] INFO: [Added] Number of AMF-UEs is now 1 (../src/amf/context.c:1143)
amf              | 07/02 18:50:13.345: [gmm] INFO: Registration request (../src/amf/gmm-sm.c:130)
amf              | 07/02 18:50:13.345: [gmm] INFO: [suci-0-001-01-0000-0-0-0000000001]    SUCI (../src/amf/gmm-handler.c:156)
ue1              | [2021-07-02 18:50:13.344] [nas] [info] UE switches to state [MM-REGISTER-INITIATED]
ue1              | [2021-07-02 18:50:13.344] [rrc] [debug] Sending RRC Setup Request
ue1              | [2021-07-02 18:50:13.344] [rrc] [info] RRC connection established
ue1              | [2021-07-02 18:50:13.344] [rrc] [info] UE switches to state [RRC-CONNECTED]
ue1              | [2021-07-02 18:50:13.344] [nas] [info] UE switches to state [CM-CONNECTED]
ue1              | [2021-07-02 18:50:13.348] [nas] [debug] Authentication Request received
ue1              | [2021-07-02 18:50:13.348] [nas] [debug] Sending Authentication Failure due to SQN out of range
amf              | 07/02 18:50:13.348: [gmm] WARNING: Authentication failure(Synch failure) (../src/amf/gmm-sm.c:503)
udm              | 07/02 18:50:13.348: [udm] ERROR: [suci-0-001-01-0000-0-0-0000000001] Re-synch MAC failed (../src/udm/nudm-handler.c:127)
udm              | [MAC_S] 0000: eb5d132f 89bb2056                     .]./.. V
udm              | 0000: 08de48a3 4212a404                     ..H.B...
udm              | 0000: 49dbd404 0104                         I.....
ausf             | 07/02 18:50:13.349: [ausf] ERROR: [suci-0-001-01-0000-0-0-0000000001] HTTP response error [401] (../src/ausf/ue-sm.c:129)
amf              | 07/02 18:50:13.349: [gmm] ERROR: [suci-0-001-01-0000-0-0-0000000001] HTTP response error [401] (../src/amf/gmm-sm.c:603)
amf              | 07/02 18:50:13.349: [amf] WARNING: [suci-0-001-01-0000-0-0-0000000001] Registration reject [111] (../src/amf/nas-path.c:154)
gnb              | [2021-07-02 18:50:13.349] [ngap] [debug] UE Context Release Command received
gnb              | [2021-07-02 18:50:13.349] [rrc] [info] Releasing RRC connection for UE[3]
amf              | 07/02 18:50:13.350: [amf] INFO: UE Context Release [Action:3] (../src/amf/ngap-handler.c:1328)
amf              | 07/02 18:50:13.350: [amf] INFO:     RAN_UE_NGAP_ID[3] AMF_UE_NGAP_ID[3] (../src/amf/ngap-handler.c:1329)
amf              | 07/02 18:50:13.350: [amf] INFO:     SUCI[suci-0-001-01-0000-0-0-0000000001] (../src/amf/ngap-handler.c:1332)
amf              | 07/02 18:50:13.350: [amf] INFO: [Removed] Number of gNB-UEs is now 0 (../src/amf/context.c:1967)
amf              | 07/02 18:50:13.350: [amf] INFO: [Removed] Number of AMF-UEs is now 0 (../src/amf/context.c:1224)
ue1              | [2021-07-02 18:50:13.350] [rrc] [debug] RRC Release received
ue1              | [2021-07-02 18:50:13.350] [nas] [error] Initial Registration failed [UNSPECIFIED_PROTOCOL_ERROR]
ue1              | [2021-07-02 18:50:13.350] [nas] [debug] Handling Registration Reject abnormal case
ue1              | [2021-07-02 18:50:13.350] [nas] [info] UE switches to state [5U2-NOT-UPDATED]
ue1              | [2021-07-02 18:50:13.350] [nas] [info] UE switches to state [MM-DEREGISTERED/ATTEMPTING-REGISTRATION]
ue1              | [2021-07-02 18:50:13.350] [nas] [info] UE switches to state [CM-IDLE]
gnb              | [2021-07-02 18:50:14.611] [rls] [debug] UE[2] signal lost
ue1              | [2021-07-02 18:50:29.340] [nas] [debug] NAS timer[3520] expired [1]
ue1              | [2021-07-02 18:50:29.340] [nas] [error] Network failing the authentication check
```

I'm using Open5GS v2.3.1 and the latest UERANSIM from the repo. These are the logs when I start a `nr-ue`. I'm trying to narrow down the issue and haven't been able to successfully so far. If this is an issue with Open5GS feel free to point me that direction and I'll open an issue over there instead.

Here are my configs:

ue.yaml
```
# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 or 16 digits)
supi: 'imsi-001010000000001'
# Mobile Country Code value of HPLMN
mcc: '001'
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '01'

# Permanent subscription key
key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
# Operator code (OP or OPC) of the UE
op: 'E8ED289DEBA952E4283B54E88E6183CA'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 192.168.29.65

# UAC Access Identities Configuration
uacAic:
  mps: false
  mcs: false

# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: 1

# Default Configured NSSAI for this UE
default-nssai:
  - sst: 1
    sd: 1

# Supported encryption algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true

# Supported integrity algorithms by this UE
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
```

gnb.yaml
```
mcc: '001'          # Mobile Country Code value
mnc: '01'           # Mobile Network Code value (2 or 3 digits)

nci: '0x000000010'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 1              # Tracking Area Code

linkIp: 192.168.29.65   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 192.168.29.65   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 192.168.29.65    # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:
  - address: 192.168.26.60
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
```

amf.yaml <snip>
```
amf:
    sbi:
      - addr: 192.168.26.60
        port: 7777
    ngap:
      - addr: 192.168.26.60
    guami:
      - plmn_id:
          mcc: 001
          mnc: 01
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: 001
          mnc: 01
        tac: 1
    plmn_support:
      - plmn_id:
          mcc: 001
          mnc: 01
        s_nssai:
          - sst: 1
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: Open5GS-gNB
    amf_name: open5gs-amf0
```

Any help would be greatly appreciated.
