### ISSUE TITLE
[error] No PLMN could be selected among [1] PLMNs

### ISSUE THREAD

**Issue by ssitpe** [aligungr/UERANSIM#383]
UE cannot connect at all. gNB can connect to open5gs core. But when UE tries to connect, it fails, no packet comes to core.
Core is open5Gs. Latest version.
UE and gNB in same VM, open5gs in another VM.

UE Log
./nr-ue -c ../config/open5gs-ue.yaml
UERANSIM v3.2.3
[2021-08-26 09:24:52.125] [rrc] [debug] New signal detected for cell[1], total [1] cells in coverage
[2021-08-26 09:24:52.126] [nas] [info] UE switches to state [MM-DEREGISTERED/PLMN-SEARCH]
[2021-08-26 09:24:54.326] [nas] [error] No PLMN could be selected among [1] PLMNs
[2021-08-26 09:24:56.528] [nas] [error] No PLMN could be selected among [1] PLMNs
[2021-08-26 09:24:57.126] [rrc] [info] Selected cell plmn[001/01] tac[1] category[ACCEPTABLE]
[2021-08-26 09:24:57.126] [nas] [info] UE switches to state [MM-DEREGISTERED/PS]
[2021-08-26 09:24:57.126] [nas] [info] UE switches to state [MM-DEREGISTERED/LIMITED-SERVICE]

gNB Log
./nr-gnb -c ../config/open5gs-gnb.yaml
UERANSIM v3.2.3
[2021-08-26 09:24:18.294] [sctp] [info] Trying to establish SCTP connection... (192.168.56.120:38412)
[2021-08-26 09:24:18.319] [sctp] [info] SCTP connection established (192.168.56.120:38412)
[2021-08-26 09:24:18.320] [sctp] [debug] SCTP association setup ascId[3]
[2021-08-26 09:24:18.320] [ngap] [debug] Sending NG Setup Request
[2021-08-26 09:24:18.323] [ngap] [debug] NG Setup Response received
[2021-08-26 09:24:18.323] [ngap] [info] NG Setup procedure is successful

[2021-08-26 09:24:52.124] [rrc] [debug] UE[1] new signal detected

gNB config
```
mcc: '001'          # Mobile Country Code value
mnc: '01'           # Mobile Network Code value (2 or 3 digits)

nci: '0x000000010'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 1              # Tracking Area Code

linkIp: 127.0.0.1   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 192.168.56.121   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 192.168.56.121    # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:
  - address: 192.168.56.120
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true

```

UE config
```
# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
supi: 'imsi-001010000000001'
# Mobile Country Code value of HPLMN
mcc: '001'
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '001'

# Permanent subscription key
key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
# Operator code (OP or OPC) of the UE
op: 'E8ED289DEBA952E4283B54E88E6183CA'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 127.0.0.1

# UAC Access Identities Configuration
uacAic:
  mps: false
  mcs: false

# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: 1

# Default Configured NSSAI for this UE
default-nssai:
  - sst: 1
    sd: 1

# Supported encryption algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true

# Supported integrity algorithms by this UE
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'

```
