### ISSUE TITLE
Security missmatch

### ISSUE THREAD

**Issue by mancubus77** [aligungr/UERANSIM#391]
UE having an issue connect with AMF and failing with UE_SECURITY_CAP_MISMATCH error. I tried 3.2.[0,1,2] versions, but result is same. 

UE
```
UERANSIM v3.2.0
[2021-09-03 02:46:00.484] [nas] [info] UE switches to state [MM-DEREGISTERED/PLMN-SEARCH]
[2021-09-03 02:46:00.485] [rrc] [debug] New signal detected for cell[1], total [1] cells in coverage
[2021-09-03 02:46:00.485] [nas] [info] Selected plmn[208/93]
[2021-09-03 02:46:00.485] [rrc] [info] Selected cell plmn[208/93] tac[70] category[SUITABLE]
[2021-09-03 02:46:00.485] [nas] [info] UE switches to state [MM-DEREGISTERED/PS]
[2021-09-03 02:46:00.485] [nas] [info] UE switches to state [MM-DEREGISTERED/NORMAL-SERVICE]
[2021-09-03 02:46:00.485] [nas] [debug] Initial registration required due to [MM-DEREG-NORMAL-SERVICE]
[2021-09-03 02:46:00.485] [nas] [debug] Sending Initial Registration
[2021-09-03 02:46:00.485] [nas] [info] UE switches to state [MM-REGISTER-INITIATED]
[2021-09-03 02:46:00.485] [rrc] [debug] Sending RRC Setup Request
[2021-09-03 02:46:00.486] [rrc] [info] RRC connection established
[2021-09-03 02:46:00.486] [rrc] [info] UE switches to state [RRC-CONNECTED]
[2021-09-03 02:46:00.486] [nas] [info] UE switches to state [CM-CONNECTED]
[2021-09-03 02:46:00.493] [rrc] [debug] RRC Release received
[2021-09-03 02:46:00.493] [nas] [error] Initial Registration failed [UE_SECURITY_CAP_MISMATCH]
[2021-09-03 02:46:00.493] [nas] [debug] Handling Registration Reject abnormal case
[2021-09-03 02:46:00.493] [nas] [info] UE switches to state [MM-DEREGISTERED/ATTEMPTING-REGISTRATION]
[2021-09-03 02:46:00.493] [nas] [info] UE switches to state [CM-IDLE]
```

Open5G AMF
```
open5gs-amf-deployment-5579ccfb9-zwfc9 amf 09/03 02:46:00.487: [gmm] ERROR: [UE:0xf0:0xf0], NEA0 can be used in Encrypt[0x0], but Integrity[0x0] cannot be bypassed with NIA0 (../src/amf/gmm-handler.c:184)
open5gs-amf-deployment-5579ccfb9-zwfc9 amf 09/03 02:46:00.487: [amf] WARNING: [suci-0-208-93-0000-0-0-0000000001] Registration reject [23] (../src/amf/nas-path.c:139)
open5gs-amf-deployment-5579ccfb9-zwfc9 amf 09/03 02:46:00.487: [gmm] ERROR: gmm_handle_registration_request() failed (../src/amf/gmm-sm.c:135)
```

UE Config 
```
# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
supi: 'imsi-901700000000001'
# Mobile Country Code value of HPLMN
mcc: '208'
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '93'
tac: '70'

# Permanent subscription key
key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
# Operator code (OP or OPC) of the UE
op: 'E8ED289DEBA952E4283B54E88E6183CA'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643804'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816152'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 192.168.50.53

# UAC Access Identities Configuration
uacAic:
  mps: false
  mcs: false

# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: 1

# Default Configured NSSAI for this UE
default-nssai:
  - sst: 1

# Supported encryption algorithms by this UE
integrity:
  IA0: true
  IA1: true
  IA2: true
  IA3: true

# Supported integrity algorithms by this UE
ciphering:
  EA0: true
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
```

AMF config 
```
logger:
    file: /var/log/open5gs/amf.log
    #level: debug
    #domain: sbi
amf:
    sbi:
    - addr: 0.0.0.0
      advertise: open5gs-amf
    ngap:
      dev: eth0
    guami:
      - plmn_id:
          mcc: 208
          mnc: 93
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: 208
          mnc: 93
        tac: 70
    plmn_support:
    - plmn_id:
        mcc: 208
        mnc: 93
      s_nssai:
      - sst: 1
        sd: 1
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: Open5GS
    amf_name: open5gs-amf0
nrf:
 sbi:
   name: open5gs-nrf 
```

**Comment by mancubus77** [comment]
UE Capabilities
<img width="348" alt="image" src="https://user-images.githubusercontent.com/16170560/131958870-117a6a48-a2bd-4ecd-bf77-22cf0aa5f9f2.png">

**Comment by aligungr** [comment]
@mancubus77  Which version of Open5gs are you using?

**Comment by mancubus77** [comment]
@aligungr thanks for help mate. Open5gs version is 2.2.2 
It was a configuration issue. Here is right config:
```
# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 or 16 digits)
supi: 'imsi-208930000000001'
# Mobile Country Code value of HPLMN
mcc: '208'
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '93'

# Permanent subscription key
key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
# Operator code (OP or OPC) of the UE
op: 'E8ED289DEBA952E4283B54E88E6183CA'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 192.168.50.53

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1
      sd: 1
    emergency: false

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: 1
    sd: 1

# Default Configured NSSAI for this UE
default-nssai:
  - sst: 1
    #sd: 1

# Supported encryption algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true

# Supported integrity algorithms by this UE
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'

# UAC Access Identities Configuration
uacAic:
  mps: false
  mcs: false

# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false
```
Closing now
