### ISSUE TITLE
run ue error: terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by zh7606559342012** [aligungr/UERANSIM#457]
hi,guys:
when i use release 3.2.4 ,config gnb and ue yaml
then to run 
build/nr-gnb -c config/open5gs-gnb.yaml   &&  build/nr-ue -c config/open5gs-ue.yaml
i can see the log the gnb start is right,i can see the tcpdump that ngrequest and response
but when i run ue ,it ouput is error,

[2021-12-08 17:33:33.116] [nas] [debug] Sending PDU Session Establishment Request
[2021-12-08 17:33:33.117] [nas] [debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[2021-12-08 17:33:33.317] [nas] [debug] Configuration Update Command received
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

i make and config depend on your web guide step by step
https://nickvsnetworking.com/my-first-5g-core-open5gs-and-ueransim/

i use centos7.9    ue and gnb on the Virtual Machine, open5gs on the another one
when the error happen,i try to solve the problem,looking the error on the internet.almost say i should change my memory more.
i use   free -m -h       it display our machine memory availble still has 12G

could you give me some adivces to solve the problem?
please, thy
                                          Astin

**Comment by zh7606559342012** [comment]
my gnb conf
```
mcc: '001'          # Mobile Country Code value
mnc: '01'           # Mobile Network Code value (2 or 3 digits)

nci: '0x000000010'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 81              # Tracking Area Code

linkIp: 192.168.20.223   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 192.168.20.223   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 192.168.20.223    # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:
  - address: 192.168.21.157
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1
    sd: 1

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
```

my ue config
````
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 192.168.20.223

# UAC Access Identities Configuration
uacAic:
  mps: false
  mcs: false

# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'cmnet'
    slice:
      sst: 1
      sd: 000001

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: 1
    sd: 000001

# Default Configured NSSAI for this UE
default-nssai:
  - sst: 1
    sd: 000001

# Supported integrity algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true

# Supported encryption algorithms by this UE
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
````
