### ISSUE TITLE
UE Configuration with free5gc

### ISSUE THREAD

**Issue by wheam2002** [aligungr/UERANSIM#459]
In config free5gc-ue.yaml, supi and imei is supported, i want to ask if GUAMI or 5G-GUTI can support ueransim or depends on free5gc? 

Thank you!
```yaml
# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
supi: 'imsi-208930000000003'
......
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'
```
