### ISSUE TITLE
Connection timeout for the gnb when it's inside a docker container

### ISSUE THREAD

**Issue by GiovanniColonni** [aligungr/UERANSIM#496]
Hi folks, I'm facing this problem and I can't find something useful.
I have a docker container inside VM1 that runs _nr-gnb_  and **open5gs** in another machine (VM2), the configuration is:
```
linkIp: 127.0.0.1   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 127.0.0.1   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 127.0.0.1    # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:
  - address: IP_VM2 
    port: 38412
```
the output of the gnb is:
```
[2022-03-08 10:44:03.939] [sctp] [info] Trying to establish SCTP connection... (<VM1>:38412) 
[2022-03-08 10:49:08.019] [sctp] [error] Connecting to <VM1>:38412 failed. SCTP could not connect
```
I try to capture the traffic between them and I can see that is the gnb that send the ABORT chunck (here the capture 
[ueransim_docker.txt](https://github.com/aligungr/UERANSIM/files/8208430/ueransim_docker.txt)) immediatly after the INIT_ACK like:

`
VM1 -> INIT -> VM2 ,
VM2 -> INIT_ACK -> VM2 ,
VM1 -> ABORT -> VM2
`
Also there are no cause inside the abort chuck that suggest what is the problem.
From the AMF side the log is:

`
03/08 10:20:35.763: [amf] INFO: [Removed] Number of gNBs is now 0 (../src/amf/context.c:897)

03/08 10:20:35.765: [amf] INFO: [Removed] Number of gNB-UEs is now 0 (../src/amf/context.c:2070)
03/08 10:20:37.670: [amf] INFO: gNB-N2 accepted[VM2]:46732 in ng-path module (../src/amf/ngap-sctp.c:105)
03/08 10:20:37.670: [amf] INFO: gNB-N2 accepted[VM2] in master_sm module (../src/amf/amf-sm.c:619)
03/08 10:20:37.670: [amf] INFO: [GNB] max_num_of_ostreams : 30 (../src/amf/context.c:854)
03/08 10:20:37.670: [amf] INFO: [Added] Number of gNBs is now 1 (../src/amf/context.c:869)
03/08 10:20:40.490: [amf] INFO: gNB-N2[VM2] connection refused!!! (../src/amf/amf-sm.c:668)
03/08 10:20:40.490: [amf] INFO: [Removed] Number of gNBs is now 0 (../src/amf/context.c:897)
03/08 10:46:30.761: [amf] INFO: [d9308e28-9e03-41ec-8edb-89be6f62599d] Subscription validity expired (../src/amf/amf-sm.c:553)
`
If i run the gnb from the VM1 with basically the same setting of the file above I have no problem at all and I can connect to the AMF.

any suggestions?
