### ISSUE TITLE
OAI + UERANSIM Integration

### ISSUE THREAD

**Issue by chandan-vp** [aligungr/UERANSIM#676]
Hello,
I am deploying OAI as 5G CN along with UERANSIM. I am following the official documentation of OAI to deploy CN with UERANSIM. 
Documentation - https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-fed/-/blob/master/docs/DEPLOY_SA5G_WITH_UERANSIM.md

As of now CN is up and healthy. When I try to run UERANSIM via docker, its shows an error as below: 

`ueransim  | [2023-10-16 04:01:34.405] [nas] [error] [IA0] cannot be accepted as the UE does not have an emergency
ueransim  | [2023-10-16 04:01:34.405] [nas] [error] Rejecting Security Mode Command with cause [SEC_MODE_REJECTED_UNSPECIFIED]
`

I have looked into the past issues and found that I have to disable NIA0 in amf's config. I did the changes and yet I am still facing the same issue. Below is the AMF's config attached: 
 
[oai-amf.txt](https://github.com/aligungr/UERANSIM/files/12912765/oai-amf.txt)

Kindly help me out in resolving this.

**Comment by massicinho** [comment]
Hi Chandan, all the steps are explained here : https://github.com/AIDY-F2N/OAI-UERANSIM

**Comment by tariromukute** [comment]
Hi @chandan-vp, you can run the OAI without integrity algorithm IA0. Comment it out in the config file, e.g., in `oai-cn5g-fed/docker-compose/conf/basic_nrf_config.yaml` like below.

```yaml
  supported_integrity_algorithms:
    # - "NIA0"
    - "NIA1"
    - "NIA2"
  supported_encryption_algorithms:
    # - "NEA0"
    - "NEA1"
    - "NEA2"
```
