### ISSUE TITLE
SCTP connection refused

### ISSUE THREAD

**Issue by Iverson-Zheng** [aligungr/UERANSIM#75]
Hello everyone, I meet some questions when doing the test of ue-ran-sim connection with Open5GS. According to the app.log, it seemed due to SCTP connection
I followed the instruction of issue #68  , #71 , I placed the gnb.yaml and ue_i2i.yaml in the same directory with ueransim-1..0.8.jar.
**gnb.yaml** is set as follows.
```
gnbId: 1

gnbPlmn:
  mcc: 901
  mnc: 70

amfConfigs:
  - guami:
      mcc: 901
      mnc: 70
      amfRegionId:
        hex: '02'
      amfSetId:
        hex: '0001'
      amfPointer:
        hex: 'a8'
    host: 127.0.0.1
    port: 38421
    isMocked: false
    mockingFile: mockedAmf.yaml

supportedTAs:
  - tac:
      hex: '000001'
    broadcastPlmns:
      - plmn:
          mcc: 901
          mnc: 70
        taiSliceSupportNssais:
          - sst:
              value: 1
            sd:
              value:
                hex: '010203
```
[gnb.yaml.txt](https://github.com/aligungr/ue-ran-sim/files/5016662/gnb.yaml.txt)

**ue_i2i.yaml**  is set as follows
[ue_i2i.yaml.txt](https://github.com/aligungr/ue-ran-sim/files/5016666/ue_i2i.yaml.txt)

```
`snn: '5G:mnc70.mcc901.3gppnetwork.org'
key: '465b5ce8b199b49faa5f0a2ee238a001'
op: 'cdc202d5123e20f62b6d676ac72cb318'
amf: '8000'
imei: '356938035643809'
supi: 'imsi-901070000000001'

smsOverNasSupported: true

requestedNssai:
  - sst:
      value: 1
    sd:
      hex: 010203

userLocationInformationNr:
  nrCgi:
    plmn:
      mcc: 901
      mnc: 70
    nrCellIdentity:
      hex: '01b2c3d4e0'
  tai:
    mcc: 901
    mnc: 70
    tac: '000001'
  timeStamp:
    hex: 5b5fa680`
```

On the other hand, the config of my **Open5GS amf.yaml** is seen as below
```
`amf:
    sbi:
      - addr: 127.0.0.2
        port: 7777
    ngap:
       addr: 127.0.0.1
    guami:
      - plmn_id:
          mcc: 901
          mnc: 70
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: 901
          mnc: 70
        tac: 1
    plmn:
      - plmn_id:
          mcc: 901
          mnc: 70
        s_nssai:
          - sst: 1
    security:
        integrity_order : [ EIA1, EIA2, EIA0 ]
        ciphering_order : [ EEA0, EEA1, EEA2 ]
    network_name:
        full: Open5GS
    amf_name: open5gs-amf0

nrf:
    sbi:
      - addr:
          - 127.0.0.1
          - ::1
        port: 7777`
```

For clearity , I also attached the **app.log**
```
`[2020-08-03 22:25:38.327] [DEBUG] [SYSTEM] UeSimContext has started: e4f1fc05-e8bb-4796-ba50-01790e788086[0m
[2020-08-03 22:25:38.328] [DEBUG] [SYSTEM] GnbSimContext has started: 92a1ce2f-431d-432f-aaea-fd55ebd13914
[2020-08-03 22:25:38.329] [INFO] [CONNECTION] Trying to establish SCTP connection... (127.0.0.1:38421)
[0;91m[2020-08-03 22:25:38.340] [ERROR] [SYSTEM] java.lang.RuntimeException: java.net.ConnectException: Connection refused at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:52)
Caused by: java.net.ConnectException: Connection refused
	at jdk.sctp/sun.nio.ch.sctp.SctpNet.connect0(Native Method)
	at jdk.sctp/sun.nio.ch.sctp.SctpNet.connect(SctpNet.java:68)
	at jdk.sctp/sun.nio.ch.sctp.SctpChannelImpl.connect(SctpChannelImpl.java:378)
	at jdk.sctp/sun.nio.ch.sctp.SctpChannelImpl.connect(SctpChannelImpl.java:445)
	at jdk.sctp/com.sun.nio.sctp.SctpChannel.open(SctpChannel.java:226)
	at tr.havelsan.ueransim.sctp.SctpClient.start(SctpClient.java:63)
	at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:49)
[0m`
```

If you have any suggestions, please help me. Sorry for putting so many words.
Thank you very much.

**Comment by s5uishida** [comment]
@Iverson-Zheng 

Is Open5GS's sctp LISTENing on **`38421/tcp`**?

In case of free5GC, it was as follows.
```
# netstat -na|grep sctp
sctp                127.0.0.1:38412                                 LISTEN
```

**Comment by Iverson-Zheng** [comment]
> @Iverson-Zheng
> 
> Is Open5GS's sctp LISTENing on **`port=38421`**?
> 
> In case of free5GC, it was as follows.
> 
> ```
> # netstat -na|grep sctp
> sctp                127.0.0.1:38412                                 LISTEN
> ```

Sorry, I'm not clear. Do you mean I need to check the LISTEN port of SCTP right ? Would you mind explaining more details?
Thanks a lot.

**Comment by s5uishida** [comment]
I think that AMF is LISTENing with sctp, so it will be necessary to set this port number in gnb.yaml.

I think that ngap between gNB and AMF is transfered over sctp.

**Comment by Iverson-Zheng** [comment]
> I think that AMF is LISTENing with sctp, so it will be necessary to set this port number in gnb.yaml.
> 
> I think that ngap between gNB and AMF is transfered over sctp.

I got it, So I need to check the SCTP port of Open5GS first and then set correct port in gnb.yaml. Is it right ?

**Comment by s5uishida** [comment]
I think it's good.

For free5GC, I found the AMF's sctp port in that way.

**Comment by Iverson-Zheng** [comment]
> I think it's good.
> 
> For free5GC, I found the AMF's sctp port in that way.

Hello, I followed your advice and check the corresponding SCTP port. But I found three SCTP ports mentioned in Open5GS.

```
sctp                127.0.0.3:5868                                  LISTEN     
sctp                127.0.0.1:38412                                 LISTEN     
sctp                127.0.0.3:3868                                  LISTEN
```
In gnb.yaml, it only contains one host and port. How to deal this situation ?

**Comment by s5uishida** [comment]
Since your **`amf.yaml`** is as below,
```
amf:
    sbi:
      - addr: 127.0.0.2
        port: 7777
    ngap:
       addr: 127.0.0.1
...
```
Maybe the following is correct.
```
sctp                127.0.0.1:38412                                 LISTEN
```
