### ISSUE TITLE
amfConfigs address IPv6 failed

### ISSUE THREAD

**Issue by adjivas** [aligungr/UERANSIM#754]
Hello,

It seems Ueransim do not correctly identifying the IPv6 address field of the AMF configuration.

When I try to use Ueransim with a IPv6 AMF, I have this error: 
```shell
% nr-gnb -c config/adjivas-free5gc-gnb.yaml
UERANSIM v3.2.6
[2025-02-18 18:26:47.087] [sctp] [info] Trying to establish SCTP connection... (2001:db8::1:0:0:18:38412)
[2025-02-18 18:26:47.089] [sctp] [error] Connecting to 2001:db8::1:0:0:18:38412 failed. SCTP could not connect: Connection refused
```

That my full config file:
```yaml
mcc: "208" # Mobile Country Code value
mnc: "93" # Mobile Network Code value (2 or 3 digits)

nci: "0x000000010" # NR Cell Identity (36-bit)
idLength: 32 # NR gNB ID length in bits [22...32]
tac: 1 # Tracking Area Code

linkIp: "2001:db8::1:0:0:17" # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: "2001:db8::1:0:0:17" # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: "2001:db8::1:0:0:17" # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:
  - address: "2001:db8::1:0:0:18"
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 0x1
    sd: 0x010203
  - sst: 0x1
    sd: 0x112233

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
```
