### ISSUE TITLE
Multiple PDU Sessions in the same APN and Slice

### ISSUE THREAD

**Issue by ghost** [aligungr/UERANSIM#756]
Hi!

I'm trying to set up multiple PDU Sessions for a single device, but also in the same APN and Slice. The `open5gs-ue.yaml` `session` section currently looks like this:

```yaml
sessions:
  - type: 'IPv4'
    apn: 'backhaul'
    slice:
      sst: 1
  - type: 'IPv4'
    apn: 'clients'
    slice:
      sst: 1
  - type: 'IPv4'
    apn: 'clients'
    slice:
      sst: 1
  - type: 'IPv4'
    apn: 'clients'
    slice:
      sst: 1
```

But only the first two are being created as per the log

```bash
[nas] [debug] PDU Session Establishment Accept received
[nas] [info] PDU Session establishment is successful PSI[1]
[nas] [debug] PDU Session Establishment Accept received
[nas] [info] PDU Session establishment is successful PSI[2]
[app] [info] Connection setup for PDU session[1] is successful, TUN interface[uesimtun0, 10.45.0.5] is up.
[app] [info] Connection setup for PDU session[2] is successful, TUN interface[uesimtun1, 10.46.0.5] is up.
```

And even when I try to manually establish the PDU Session via the `nr-cli`executable, the new Session remains in the state of `PS-ACTIVE-PENDING`, and eventually fails.

```bash
$ ps-establish IPv4 --sst 1 --sd 1 --dnn clients
PDU session establishment procedure triggered
--------------------------------------------------------------------------------------------
$ ps-list
PDU Session1: 
 state: PS-ACTIVE
 session-type: IPv4
 apn: backhaul
 s-nssai: 
  sst: 0x01
  sd: null
 emergency: false
 address: 10.45.0.6
 ambr: up[1000000Kb/s] down[1000000Kb/s]
 data-pending: false
PDU Session2: 
 state: PS-ACTIVE
 session-type: IPv4
 apn: clients
 s-nssai: 
  sst: 0x01
  sd: null
 emergency: false
 address: 10.46.0.6
 ambr: up[1000000Kb/s] down[1000000Kb/s]
 data-pending: false
PDU Session3: 
 state: PS-ACTIVE-PENDING
 session-type: IPv4
 apn: clients
 s-nssai: 
  sst: 0x01
  sd: 0x000001
 emergency: false
 address: null
 ambr: null
 data-pending: false
```

This didn't happen before when I configured each PDU Sessions in separate APNs, but that is not my desired use case.

Do you have any idea of what might be the issue here?

Greatly appreciate the help, thanks!
